# Generated by Django 4.1 on 2023-04-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservationNumber',
            field=models.IntegerField(unique=True),
        ),
    ]
