# Generated by Django 4.1 on 2023-04-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flightApp', '0005_remove_reservation_reservationnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='phoneNumber',
            field=models.CharField(max_length=10),
        ),
    ]
